# Generated by Django 4.0.5 on 2022-06-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricula', models.PositiveIntegerField(default=5)),
                ('Responsable', models.CharField(max_length=255)),
                ('Entrenamiento', models.CharField(max_length=255)),
                ('Mascota', models.CharField(max_length=255)),
                ('Pagado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Responsable', models.CharField(max_length=255)),
                ('Matricula', models.PositiveIntegerField(default=5)),
                ('Entrenamiento', models.CharField(max_length=255)),
                ('DNI', models.PositiveIntegerField(default=9)),
                ('Nombre', models.CharField(max_length=255)),
                ('Apellidos', models.CharField(max_length=255)),
                ('Direccion', models.CharField(max_length=255)),
                ('Correo', models.EmailField(max_length=254)),
                ('Movil', models.PositiveIntegerField(default=9)),
            ],
        ),
    ]
