# Generated by Django 4.0.5 on 2022-06-29 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='Entrenamiento',
            new_name='entrenamiento',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='Mascota',
            new_name='mascota',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='Pagado',
            new_name='pagado',
        ),
        migrations.RenameField(
            model_name='matricula',
            old_name='Responsable',
            new_name='responsable1',
        ),
        migrations.RenameField(
            model_name='responsable',
            old_name='Apellidos',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='responsable',
            old_name='Correo',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='responsable',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='responsable',
            old_name='DNI',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='responsable',
            old_name='Entrenamiento',
            new_name='entrenamiento',
        ),
        migrations.RenameField(
            model_name='responsable',
            old_name='Movil',
            new_name='movil',
        ),
        migrations.RenameField(
            model_name='responsable',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='Matricula',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='Matricula',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='Responsable',
        ),
        migrations.AddField(
            model_name='responsable',
            name='matricula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academiapp.matricula'),
        ),
    ]
