# Generated by Django 4.0.5 on 2022-06-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiapp', '0002_rename_entrenamiento_matricula_entrenamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsable',
            name='dni',
            field=models.CharField(max_length=255),
        ),
    ]
