# Generated by Django 4.0.5 on 2022-06-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiapp', '0003_alter_responsable_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('aprobado', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='matricula',
        ),
        migrations.DeleteModel(
            name='Matricula',
        ),
        migrations.DeleteModel(
            name='Responsable',
        ),
    ]
