# Generated by Django 4.0.5 on 2022-06-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiapp', '0004_curso_remove_responsable_matricula_delete_matricula_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='aprobado',
            new_name='matriculada',
        ),
    ]
