# Generated by Django 4.0.5 on 2022-06-30 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiapp', '0005_rename_aprobado_curso_matriculada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
