# Generated by Django 4.0.5 on 2022-07-01 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academiapp', '0006_delete_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('completado', models.BooleanField()),
                ('pagado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('especie', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=20)),
                ('dni_Responsable', models.CharField(max_length=20)),
                ('nombre_Responsable', models.CharField(max_length=20)),
                ('apellido_Responsable', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('pass1', models.CharField(max_length=10)),
                ('asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academiapp.asignatura')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='mascota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academiapp.mascota'),
        ),
    ]
