# Generated by Django 4.0.5 on 2022-07-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiapp', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenadora',
            name='pass1',
        ),
    ]
