# Generated by Django 4.0.5 on 2022-07-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiapp', '0008_remove_entrenadora_pass1'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='email_Responsable',
            field=models.EmailField(default='name@yahoo.com', max_length=30),
        ),
    ]
