# Generated by Django 4.0.5 on 2022-07-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academiapp', '0010_remove_mascota_apellido_responsable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienta',
            name='mascota_id',
        ),
        migrations.AddField(
            model_name='mascota',
            name='clienta_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academiapp.clienta'),
        ),
    ]
