# Generated by Django 4.0.5 on 2022-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiapp', '0011_remove_clienta_mascota_id_mascota_clienta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienta',
            name='movil_Responsable',
            field=models.IntegerField(default=234567890),
        ),
    ]
