# Generated by Django 4.0.5 on 2022-07-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiapp', '0014_mascota_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='user_id',
            new_name='usuario_id',
        ),
    ]
