# Generated by Django 4.0.5 on 2022-07-05 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academiapp', '0015_rename_user_id_mascota_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='usuario_id',
        ),
        migrations.AddField(
            model_name='mascota',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
