# Generated by Django 4.0.5 on 2022-07-05 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academiapp', '0016_remove_mascota_usuario_id_mascota_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='usuario',
        ),
        migrations.AddField(
            model_name='mascota',
            name='usuario_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
