# Generated by Django 4.0.5 on 2022-07-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academiapp', '0017_remove_mascota_usuario_mascota_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='usuario_id',
        ),
    ]
